name: CMake

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-macos-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build x86_64
        run: ./makemac.sh -arch x86_64 -sb --pack --skip-samples

      - name: Test
        working-directory: ${{github.workspace}}/.vs
        run: ./msixtest/msixtest

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: makemsix-darwin-x64
          path: |
            .vs/bin/makemsix

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build arm64
        run: ./makemac.sh -arch arm64 -sb --pack --skip-samples --skip-tests

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: makemsix-darwin-arm64
          path: |
            .vs/bin/makemsix

  build-linux-ubuntu-22:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        # Build your program with the given configuration
        run: ./makelinux.sh -sb --pack --skip-samples

      - name: Test
        working-directory: ${{github.workspace}}/.vs
        run: ./msixtest/msixtest

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: makemsix-linux-ubuntu-22-x64
          path: |
            .vs/bin/makemsix

     - name: Node
       uses: actions/setup-node@v3
       with:
         node-version: 14.x

    - run: node -e "console.log(require(\"os\").version())"

  build-linux-20:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Build
        # Build your program with the given configuration
        run: ./makelinux.sh -sb --pack --skip-samples

      - name: Test
        working-directory: ${{github.workspace}}/.vs
        run: ./msixtest/msixtest

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: makemsix-linux-ubuntu-20-x64
          path: |
            .vs/bin/makemsix

     - name: Node
       uses: actions/setup-node@v3
       with:
         node-version: 14.x

    - run: node -e "console.log(require(\"os\").version())"
